import type { ReceiptReviewDraft } from './types.ts';

/** 실제 OCR 결과가 아닌, 검수 UX를 보여 주기 위한 고정 데모 영수증이다. */
export const receiptReviewFixture: ReceiptReviewDraft = {
  batchId: 'demo-grocery-2026-08-29',
  sourceLabel: '8월 29일 장보기 영수증',
  items: [
    {
      id: 'egg',
      rawName: '신선란 10구',
      name: '계란',
      quantity: '10개',
      storage: '냉장',
      kind: 'ingredient',
      recommendedUseBy: '다음 주 안',
      recommendedUseByAt: '2026-09-05',
      confidence: 'high',
      included: true,
    },
    {
      id: 'tofu',
      rawName: '국산콩 부침두부',
      name: '두부',
      quantity: '1모',
      storage: '냉장',
      kind: 'ingredient',
      labelExpiryAt: '2026-09-02',
      recommendedUseBy: '이번 주 안',
      recommendedUseByAt: '2026-09-01',
      confidence: 'high',
      included: true,
    },
    {
      id: 'dumpling',
      rawName: '고기왕교자 2봉',
      name: '냉동만두',
      quantity: '2봉',
      storage: '냉동',
      kind: 'ingredient',
      recommendedUseBy: '여유 있음',
      recommendedUseByAt: '2026-11-30',
      confidence: 'high',
      included: true,
    },
    {
      id: 'zucchini',
      rawName: '친환경 애호박',
      name: '애호박',
      quantity: '1개',
      storage: '냉장',
      kind: 'ingredient',
      recommendedUseBy: '사흘 안',
      recommendedUseByAt: '2026-09-01',
      confidence: 'high',
      included: true,
    },
    {
      id: 'sesame-oil',
      rawName: '백설 진한참기름',
      name: '참기름',
      quantity: '1병',
      storage: '실온',
      kind: 'ingredient',
      recommendedUseBy: '여유 있음',
      confidence: 'needs-review',
      included: true,
    },
    {
      id: 'pork',
      rawName: '한돈 앞다리 불고기용',
      name: '돼지고기',
      quantity: '600g',
      storage: '냉장',
      kind: 'ingredient',
      labelExpiryAt: '2026-09-01',
      recommendedUseBy: '이틀 안',
      recommendedUseByAt: '2026-08-31',
      confidence: 'needs-review',
      included: true,
    },
  ],
};
