import type { InventoryItem } from './types';

export const seedInventory: InventoryItem[] = [
  {
    id: 'leftover-chicken',
    name: '남은 치킨',
    quantity: '1인분',
    storage: '냉장',
    recommendedUseBy: '오늘',
    recommendedUseByAt: '2026-08-29',
    reason: '어제부터 냉장 보관 중이에요.',
    kind: 'leftover',
    storageStartedAt: '어제',
    createdAt: '2026-08-25T10:00:00.000Z',
  },
  {
    id: 'tofu',
    name: '두부',
    quantity: '1모',
    storage: '냉장',
    recommendedUseBy: '이틀 안',
    recommendedUseByAt: '2026-08-31',
    reason: '개봉 전이지만 이번 주 안에 써보세요.',
    kind: 'ingredient',
    purchasedAt: '오늘',
    labelExpiryAt: '8월 29일',
    createdAt: '2026-08-26T10:00:00.000Z',
  },
  {
    id: 'zucchini',
    name: '애호박',
    quantity: '반 개',
    storage: '냉장',
    recommendedUseBy: '이틀 안',
    recommendedUseByAt: '2026-08-31',
    reason: '남은 양이 적어 먼저 쓰기 좋아요.',
    kind: 'ingredient',
    purchasedAt: '오늘',
    createdAt: '2026-08-26T10:00:00.000Z',
  },
  {
    id: 'eggs',
    name: '계란',
    quantity: '9개',
    storage: '냉장',
    recommendedUseBy: '8월 30일',
    recommendedUseByAt: '2026-08-30',
    reason: '여유 있어요.',
    kind: 'ingredient',
    labelExpiryAt: '8월 30일',
    createdAt: '2026-08-26T10:00:00.000Z',
  },
  {
    id: 'dumplings',
    name: '냉동만두',
    quantity: '2봉',
    storage: '냉동',
    recommendedUseBy: '11월 25일',
    recommendedUseByAt: '2026-11-25',
    reason: '여유 있어요.',
    kind: 'ingredient',
    labelExpiryAt: '11월 25일',
    createdAt: '2026-08-26T10:00:00.000Z',
  },
];
